#ifndef PINCONFIG_H
#define PINCONFIG_H

#define MOTOR_LEFT_FORWARD 26
#define MOTOR_LEFT_BACKWARD 27
#define MOTOR_LEFT_SPEED 14
#define MOTOR_LEFT_PWM_CHANNEL 0
#define MOTOR_RIGHT_FORWARD 13
#define MOTOR_RIGHT_BACKWARD 12
#define MOTOR_RIGHT_SPEED 5
#define MOTOR_RIGHT_PWM_CHANNEL 1
#define PWM_FREQ 30000
#define PWM_RESOLUTION 8

#define STEPPER_IN1 4
#define STEPPER_IN2 0
#define STEPPER_IN3 2
#define STEPPER_IN4 15

#define I2C_SDA 21
#define I2C_SCL 22

#define SERIAL2_RX 16
#define SERIAL2_TX 17

#endif
